/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as modules from "./modules";
export type { modules };
import type * as time from "./time";
export type { time };
export type { ERC20Token } from "./ERC20Token";
export type { Greeter } from "./Greeter";
export type { KAP20Token } from "./KAP20Token";
export type { KAP20mine } from "./KAP20mine";
