/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAdminAsset__factory } from "./IAdminAsset__factory";
export { IAdminProjectRouter__factory } from "./IAdminProjectRouter__factory";
