/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as modules from "./modules";
export * as time from "./time";
export { ERC20Token__factory } from "./ERC20Token__factory";
export { Greeter__factory } from "./Greeter__factory";
export { KAP20Token__factory } from "./KAP20Token__factory";
export { KAP20mine__factory } from "./KAP20mine__factory";
