/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKAP20KYC } from "./IKAP20KYC";
export type { IKYC } from "./IKYC";
export type { IKYCBitkubChain } from "./IKYCBitkubChain";
