/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as admin from "./admin";
export type { admin };
import type * as blacklist from "./blacklist";
export type { blacklist };
import type * as committee from "./committee";
export type { committee };
import type * as kap20 from "./kap20";
export type { kap20 };
import type * as kyc from "./kyc";
export type { kyc };
import type * as pause from "./pause";
export type { pause };
