/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKAP20KYC__factory } from "./IKAP20KYC__factory";
export { IKYC__factory } from "./IKYC__factory";
export { IKYCBitkubChain__factory } from "./IKYCBitkubChain__factory";
