/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAdminAsset } from "./IAdminAsset";
export type { IAdminProjectRouter } from "./IAdminProjectRouter";
